# -*- coding: utf-8 -*-

TITLE = 'title'
SUBTITLE = 'subtitle'
HEADING1 = 'heading1'
HEADING2 = 'heading2'
HEADING3 = 'heading3'
HEADING4 = 'heading4'
HEADING5 = 'heading5'
HEADING6 = 'heading6'

BULLET_LIST = 'bullet_list'
ENUMERATED_LIST = 'enumerated_list'
EMPTY_BULLET_LIST = '_empty_bullet_list'
DEFINITION_LIST = 'definition_list'
DEFINITION_LIST_ITEM = 'definition_list_item'
FIELD_LIST = 'field_list'
FIELD_LIST_ITEM = 'field_list_item'
OPTION_LIST = 'option_list'
OPTION_LIST_ITEM = 'option_list_item'
LITERAL_BLOCK = 'literal_block'
BLOCK_QUOTE = 'block_quote'
LINE_BLOCK = 'line_block'
DOCTEST_BLOCK = 'doctest_block'
TRANSITION = 'transition'

IMAGE_CAPTION = 'image_caption'
CODE_BLOCK_CAPTION = 'code_block_caption'
# character styles
STRONG = 'strong'
EMPHASIS = 'emphasis'
LITERAL_EMPHASIS = 'literal_emphasis'
SUBSCRIPT = 'subscript'
SUPERSCRIPT = 'superscript'
TITLE_REFERENCE = 'title_reference'
LITERAL = 'literal'
REFERENCE = 'reference'
FOOTNOTE_REFERENCE = 'footnote_reference'

INTENCE_QUOTE = 'intence_quote'

# Table styles
TABLE_CAPTION = 'table_caption'
TABLE_NORMAL = 'table'
TABLE_LIST = 'table_list'
